# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FreeKiro < Formula
  desc "Spec-driven development workflow CLI (Kiro Spec workflow in Go)"
  homepage "https://github.com/jingyu525/free-kiro"
  version "0.6.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jingyu525/free-kiro/releases/download/v0.6.0/free-kiro_0.6.0_darwin_amd64.tar.gz"
      sha256 "12abf04b578ff090d2fc64ccdd2db2566d5003cd4b1ab7869dac33889395298f"

      define_method(:install) do
        bin.install "free-kiro"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jingyu525/free-kiro/releases/download/v0.6.0/free-kiro_0.6.0_darwin_arm64.tar.gz"
      sha256 "d572f69e80fecaeae2690e73aed281162eb218f793e8d6dc6a09ba0cad5a5c7e"

      define_method(:install) do
        bin.install "free-kiro"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jingyu525/free-kiro/releases/download/v0.6.0/free-kiro_0.6.0_linux_amd64.tar.gz"
      sha256 "b77691958e75bc915dd2b3c745421ce3dadb72bff38a0a754e4e2990ed3e7eb3"
      define_method(:install) do
        bin.install "free-kiro"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jingyu525/free-kiro/releases/download/v0.6.0/free-kiro_0.6.0_linux_arm64.tar.gz"
      sha256 "3cc39830d78f0fb9b313c66937a5df660d3d3aa16f1c140b8277150f6b91f718"
      define_method(:install) do
        bin.install "free-kiro"
      end
    end
  end

  test do
    assert_match "free-kiro", ball_output("#{bin}/free-kiro --version")
  end
end
