# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FreeKiro < Formula
  desc "Spec-driven development workflow CLI (Kiro Spec workflow in Go)"
  homepage "https://github.com/jingyu525/free-kiro"
  version "0.7.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jingyu525/free-kiro/releases/download/v0.7.1/free-kiro_0.7.1_darwin_amd64.tar.gz"
      sha256 "ecc94a0afe19b78143063592b9eee2849b6cc230cc9791af19f466e54cc6279e"

      define_method(:install) do
        bin.install "free-kiro"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jingyu525/free-kiro/releases/download/v0.7.1/free-kiro_0.7.1_darwin_arm64.tar.gz"
      sha256 "e1aa57c1a8ba8f62410d80e16a311897223606eeef5a628f118917913a9373eb"

      define_method(:install) do
        bin.install "free-kiro"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jingyu525/free-kiro/releases/download/v0.7.1/free-kiro_0.7.1_linux_amd64.tar.gz"
      sha256 "205ae9de94faf47f0f010e39e67da49082804c1a110c7be87a0696ff0884ff75"
      define_method(:install) do
        bin.install "free-kiro"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jingyu525/free-kiro/releases/download/v0.7.1/free-kiro_0.7.1_linux_arm64.tar.gz"
      sha256 "4941709bffbe9ca3607216a2aca6e25d20d4153c9723635968343d3d7ee94b55"
      define_method(:install) do
        bin.install "free-kiro"
      end
    end
  end

  test do
    assert_match "free-kiro", ball_output("#{bin}/free-kiro --version")
  end
end
