# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser for free-kiro v0.5.0-test.
# Auto-updates on every release via jingyu525/free-kiro's release workflow
# (requires HOMEBREW_TAP_TOKEN secret).

class FreeKiro < Formula
  desc "Spec-driven development workflow CLI (Kiro Spec workflow in Go)"
  homepage "https://github.com/jingyu525/free-kiro"
  version "0.5.0-test"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jingyu525/free-kiro/releases/download/v0.5.0-test/free-kiro_0.5.0-test_darwin_amd64.tar.gz"
      sha256 "4c8a5124ea245fd66e47b9f4bbddf803a62fa69501ccfac5b6f575e51c8009eb"
      def install; bin.install "free-kiro"; end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jingyu525/free-kiro/releases/download/v0.5.0-test/free-kiro_0.5.0-test_darwin_arm64.tar.gz"
      sha256 "d83e7f095534b3189ab52a8cd23e00f9f2173d4aaddabe0ceec400ede4cc722c"
      def install; bin.install "free-kiro"; end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jingyu525/free-kiro/releases/download/v0.5.0-test/free-kiro_0.5.0-test_linux_amd64.tar.gz"
      sha256 "2888536c784b589b53aa4f2d2a487f9052f57f7e1362197270e3fac1e6057c1e"
      def install; bin.install "free-kiro"; end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jingyu525/free-kiro/releases/download/v0.5.0-test/free-kiro_0.5.0-test_linux_arm64.tar.gz"
      sha256 "6029dadb8c7d72b783a758c724f2ad4a4436452c5090dfbe0a32cbf20855c040"
      def install; bin.install "free-kiro"; end
    end
  end

  test do
    assert_match "free-kiro", shell_output("#{bin}/free-kiro --version")
  end
end
